### ISSUE TITLE
Estimating Bounds on Causal Effects in High-dimensional and Possibly Confounded Systems

### ISSUE THREAD

**Issue by zys07** [santikka/dosearch#1]
Hello, I am looking for "@article{MALINSKY.
title = {Estimating Bounds on Causal Effects in High-dimensional and Possibly Confounded Systems}.
journal = {International Journal of Approximate Reasoning}.
volume = {88}.
pages = {371--384}.
year = {2017}.
author = {D.~Malinsky and P.~Spirtes}.
doi= {10.1016/j.ijar.2017.06.005}
}"The code related to this paper, I see it mentioned in your document, how can I find the code related to this one?

**Comment by santikka** [comment]
Hello @zys07. I'm not sure what you're asking for here. Are you asking for the code in the paper "Estimating Bounds on Causal Effects in High-dimensional and Possibly Confounded Systems"? We do reference this paper in relation to dosearch, but not the code specifically. I don't know if the code for that paper is publicly available anywhere
